import { Router } from 'express';
import { authRouter } from './auth.js';
import { requireAuth, tenantScope, requireRoles } from '../../middleware/auth.js';
import { overview } from '../../controllers/dashboardController.js';
import { listProjects, createProject, updateProject } from '../../controllers/projectController.js';
import { listGrants, createGrant } from '../../controllers/grantController.js';
import { listPriorities, createPriority, listPathways, createPathway, listWorkItems, createWorkItem, assessReadiness, listEvidence, createEvidence } from '../../controllers/portfolioController.js';
import { createConstraint, getProjectCouncilProof, listCouncilProofSelectors, listProjectConstraints, replaceProjectSelections, updateConstraint } from '../../controllers/councilProofController.js';
import { resetDemo } from '../../controllers/demoController.js';
import { previewImport, commitImport } from '../../controllers/importController.js';
import { adminRouter } from './admin.js';
import { submitPortfolioReadinessPulse } from '../../controllers/publicPulseController.js';

export const v1Router = Router();
v1Router.get('/health', (_req, res) => res.json({ data: { service: 'civicpath-api', status: 'healthy' } }));
v1Router.use('/auth', authRouter);
v1Router.post('/public/portfolio-readiness-pulse', submitPortfolioReadinessPulse);
v1Router.use('/admin', requireAuth, tenantScope, adminRouter);
v1Router.use(requireAuth, tenantScope);
v1Router.get('/dashboard/overview', overview);
v1Router.get('/council-proof/selectors', listCouncilProofSelectors);
v1Router.get('/priorities', listPriorities);
v1Router.post('/priorities', requireRoles('org_admin', 'portfolio_manager'), createPriority);
v1Router.get('/projects', listProjects);
v1Router.post('/projects', requireRoles('org_admin', 'portfolio_manager'), createProject);
v1Router.patch('/projects/:projectId', requireRoles('org_admin', 'portfolio_manager'), updateProject);
v1Router.get('/projects/:projectId/council-proof', getProjectCouncilProof);
v1Router.put('/projects/:projectId/selectors/:selectorCode', requireRoles('org_admin', 'portfolio_manager'), replaceProjectSelections);
v1Router.get('/projects/:projectId/constraints', listProjectConstraints);
v1Router.post('/projects/:projectId/constraints', requireRoles('org_admin', 'portfolio_manager', 'contributor'), createConstraint);
v1Router.patch('/projects/:projectId/constraints/:constraintId', requireRoles('org_admin', 'portfolio_manager', 'contributor'), updateConstraint);
v1Router.post('/projects/:projectId/readiness-assessments', requireRoles('org_admin', 'portfolio_manager'), assessReadiness);
v1Router.get('/funding-pathways', listPathways);
v1Router.post('/funding-pathways', requireRoles('org_admin', 'portfolio_manager', 'contributor'), createPathway);
v1Router.get('/grants', listGrants);
v1Router.post('/grants', requireRoles('org_admin', 'portfolio_manager', 'contributor'), createGrant);
v1Router.get('/work-items', listWorkItems);
v1Router.post('/work-items', requireRoles('org_admin', 'portfolio_manager', 'contributor'), createWorkItem);
v1Router.get('/evidence', listEvidence);
v1Router.post('/evidence', requireRoles('org_admin', 'portfolio_manager', 'contributor'), createEvidence);
v1Router.post('/imports/preview', requireRoles('org_admin', 'portfolio_manager'), previewImport);
v1Router.post('/imports/commit', requireRoles('org_admin', 'portfolio_manager'), commitImport);
v1Router.post('/demo/reset', requireRoles('org_admin'), resetDemo);
