/* CivicPath shell — role-aware navigation separates Council workspaces from platform administration. */
import React, { useState } from 'react';
import { NavLink, useLocation } from 'react-router-dom';
import { Icon } from './Icon';
import { useAuth } from '../features/AuthContext';

const councilNavItems = [['/dashboard', 'Overview', 'grid'], ['/portfolio', 'Project portfolio', 'folder'], ['/funding', 'Funding pathways', 'fund'], ['/grants', 'Grant lifecycle', 'check'], ['/reports', 'Reports', 'report']];
const adminNavItems = [['/admin', 'System Admin', 'grid']];

export function AppShell({ children }) {
  const [collapsed, setCollapsed] = useState(false); const location = useLocation(); const { user, signOut } = useAuth(); const isPlatformAdmin = user?.role === 'platform_admin'; const navItems = isPlatformAdmin ? adminNavItems : councilNavItems; const label = navItems.find(([path]) => location.pathname.startsWith(path))?.[1] || (isPlatformAdmin ? 'System Admin' : 'Overview'); const initials = `${user?.firstName?.[0] || ''}${user?.lastName?.[0] || ''}` || 'CP';
  return <div className={collapsed ? 'app-shell is-collapsed' : 'app-shell'}><aside className="side-rail"><div className="rail-brand"><img src="/gate-mark.png" alt=""/><span>CivicPath</span></div><button className="workspace-switcher" type="button"><span className="workspace-mark">{isPlatformAdmin ? 'CP' : 'CD'}</span><span><b>{isPlatformAdmin ? 'CivicPath\nPlatform' : 'Demonstration\nCouncil'}</b><small>{isPlatformAdmin ? 'System administration' : 'Illustrative sample data'}</small></span><Icon name="chevron" size={15}/></button><nav className="main-nav" aria-label="Application navigation">{navItems.map(([path, name, icon]) => <NavLink key={path} to={path} className={({ isActive }) => isActive ? 'is-active' : ''}><Icon name={icon}/><span>{name}</span></NavLink>)}</nav><div className="rail-footer">{!isPlatformAdmin && <NavLink to="/settings"><Icon name="settings"/><span>Workspace settings</span></NavLink>}<button type="button" onClick={() => setCollapsed(!collapsed)} aria-label="Toggle sidebar"><span className="collapse-icon">‹</span><span>Collapse</span></button><button type="button" className="rail-user" onClick={signOut} title="Sign out"><div>{initials}</div><span><b>{user?.firstName} {user?.lastName}</b><small>{isPlatformAdmin ? 'System Administrator' : user?.role?.replace('_', ' ')}</small></span></button></div></aside><div className="application"><header className="app-header"><div><p className="crumb">CivicPath / <span>{label}</span></p><h1>{label}</h1></div><div className="header-actions"><button className="icon-button" type="button" aria-label="Search"><Icon name="search"/></button><button className="icon-button notification" type="button" aria-label="Notifications"><Icon name="bell"/><i /></button><button className="period-select" type="button">{isPlatformAdmin ? 'Platform operations' : 'This financial year'} <span>⌄</span></button></div></header>{children}</div></div>;
}
