/* CivicPath shell — role-aware navigation separates Council workspaces from platform administration. */
import React, { useState } from 'react';
import { NavLink, useLocation } from 'react-router-dom';
import { Icon } from './Icon';
import { useAuth } from '../features/AuthContext';

const councilNavItems = [['/dashboard', 'Overview', 'grid'], ['/strategy-delivery', 'Strategy delivery', 'report'], ['/portfolio', 'Project portfolio', 'folder'], ['/funding', 'Funding pathways', 'fund'], ['/grants', 'Grant lifecycle', 'check'], ['/reports', 'Reports', 'report']];
const adminNavItems = [['/admin', 'System Admin', 'grid']];

export function AppShell({ children }) {
  const [collapsed, setCollapsed] = useState(false); const location = useLocation(); const { user, signOut } = useAuth(); const isPlatformAdmin = user?.role === 'platform_admin'; const navItems = isPlatformAdmin ? adminNavItems : councilNavItems; const label = navItems.find(([path]) => location.pathname.startsWith(path))?.[1] || (location.pathname.startsWith('/settings') ? 'Workspace settings' : isPlatformAdmin ? 'System Admin' : 'Overview'); const workspaceName = user?.organisationName || 'Council workspace'; const workspaceInitials = workspaceName.split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]).join('').toUpperCase(); const initials = `${user?.firstName?.[0] || ''}${user?.lastName?.[0] || ''}` || 'CP';
  return <div className={collapsed ? 'app-shell is-collapsed' : 'app-shell'}><aside className="side-rail"><div className="rail-brand"><img src="/civicpath-quartermark.png" alt=""/><span>CivicPath</span></div><div className="workspace-switcher" aria-label="Current workspace"><span className="workspace-mark">{isPlatformAdmin ? 'CP' : workspaceInitials}</span><span><b>{isPlatformAdmin ? 'CivicPath Platform' : workspaceName}</b><small>{isPlatformAdmin ? 'System administration' : user?.organisationIsDemo ? 'Illustrative sample data' : 'Council workspace'}</small></span></div><nav className="main-nav" aria-label="Application navigation">{navItems.map(([path, name, icon]) => <NavLink key={path} to={path} className={({ isActive }) => isActive ? 'is-active' : ''}><Icon name={icon}/><span>{name}</span></NavLink>)}</nav><div className="rail-footer">{!isPlatformAdmin && <NavLink to="/settings"><Icon name="settings"/><span>Workspace settings</span></NavLink>}<button type="button" onClick={() => setCollapsed(!collapsed)} aria-label="Toggle sidebar"><span className="collapse-icon">‹</span><span>Collapse</span></button><button type="button" className="rail-user" onClick={signOut} title="Sign out"><div>{initials}</div><span><b>{user?.firstName} {user?.lastName}</b><small>{isPlatformAdmin ? 'System Administrator' : user?.role?.replace('_', ' ')}</small></span></button></div></aside><div className="application"><header className="app-header"><div><p className="crumb">CivicPath / <span>{label}</span></p><h1>{label}</h1></div><div className="header-actions"><span className="period-select">{isPlatformAdmin ? 'Platform operations' : 'This financial year'}</span></div></header><div id="main-content" tabIndex="-1">{children}</div></div></div>;
}
