import React, { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import toast from 'react-hot-toast';
import { api, importCsv } from '../lib/api';
import { Icon } from './Icon';

const entityOptions = { projects: ['Project register', 'name, priority, category, stage, estimated_cost, target_funding, expected_jobs, target_date'], grants: ['Grant register', 'title, funder, project, requested_amount, status, due_date, acquittal_due_date'] };

export function WorkspaceProfilePanel({ user }) {
  const [data, setData] = useState(null); const [form, setForm] = useState(null); const [saving, setSaving] = useState(false); const isAdmin = user?.role === 'org_admin';
  useEffect(() => { api.get('/workspace/profile').then((response) => { setData(response.data.data); setForm(response.data.data.profile); }).catch(() => toast.error('Workspace profile could not be loaded.')); }, []);
  const set = (key) => (event) => setForm((current) => ({ ...current, [key]: event.target.value }));
  const submit = async (event) => { event.preventDefault(); setSaving(true); try { const response = await api.patch('/workspace/profile', form); setForm(response.data.data); toast.success('Workspace profile saved.'); } catch (error) { toast.error(error.response?.data?.error || 'Workspace profile could not be saved.'); } finally { setSaving(false); } };
  if (!form) return <section className="settings-card"><p className="card-eyebrow">Workspace identity</p><p className="card-copy">Loading workspace profile…</p></section>;
  return <section className="settings-card"><div><p className="card-eyebrow">Workspace identity</p><h3>{form.name}</h3><p className="card-copy">Keep the accountable Council contact and workspace owner clear. Billing address and tax details are managed securely through Stripe by the Organisation Administrator.</p></div>{isAdmin ? <form className="workspace-profile-form" onSubmit={submit}><div className="field-grid"><label>Council or organisation name<input value={form.name} onChange={set('name')} required/></label><label>Country<input value={form.country === 'NZ' ? 'New Zealand' : 'Australia'} disabled/></label><label>Operating contact name<input value={form.operatingContactName || ''} onChange={set('operatingContactName')} placeholder="Primary delivery contact"/></label><label>Operating contact role<input value={form.operatingContactRole || ''} onChange={set('operatingContactRole')} placeholder="e.g. Economic Development Manager"/></label><label>Operating contact email<input type="email" value={form.operatingContactEmail || ''} onChange={set('operatingContactEmail')} placeholder="name@council.gov.au"/></label><label>Workspace owner<select value={form.workspaceOwnerId || ''} onChange={set('workspaceOwnerId')}><option value="">Choose an accountable owner</option>{data?.eligibleOwners?.map((member) => <option key={member.id} value={member.id}>{member.firstName} {member.lastName} · {member.role.replace(/_/g, ' ')}</option>)}</select></label></div><button className="secondary-button" type="submit" disabled={saving}>{saving ? 'Saving…' : 'Save workspace profile'}</button></form> : <p className="settings-readonly-note">Your Organisation Administrator manages workspace identity and accountable contacts. You can still use the workspace and submit support enquiries below.</p>}</section>;
}

export function DataImportPanel({ canManage }) {
  const [entityType, setEntityType] = useState('projects'); const [file, setFile] = useState(null); const [preview, setPreview] = useState(null); const [loading, setLoading] = useState(false); const [importing, setImporting] = useState(false);
  const selected = useMemo(() => entityOptions[entityType], [entityType]);
  const choose = async (event) => { const next = event.target.files?.[0]; if (!next) return; setFile(next); setPreview(null); setLoading(true); try { const result = await importCsv(entityType, next); setPreview(result); } catch (error) { toast.error(error.response?.data?.error || 'This CSV could not be reviewed. Use the CivicPath template and check the required columns.'); } finally { setLoading(false); } };
  const commit = async () => { if (!preview) return; setImporting(true); try { const response = await api.post('/imports/commit', { entityType, rows: preview.rows }); toast.success(`${response.data.data.created} ${entityType} imported.${response.data.data.skipped.length ? ` ${response.data.data.skipped.length} row(s) need review.` : ''}`); setFile(null); setPreview(null); } catch (error) { toast.error(error.response?.data?.error || 'The import could not be completed.'); } finally { setImporting(false); } };
  const download = entityType === 'projects' ? '/civicpath-project-import-template.csv' : '/civicpath-grant-import-template.csv';
  return <section className="settings-card import-card"><div><p className="card-eyebrow">Data import</p><h3>Start from the register you already use.</h3><p className="card-copy">CivicPath previews the prescribed columns before importing. No demonstration record is copied into a Council workspace.</p><div className="import-mapping"><b>{selected[0]} mapping</b><span>{selected[1]}</span></div><div className="import-actions"><a href={download} download>Download {entityType === 'projects' ? 'project' : 'grant'} CSV template <Icon name="external" size={14}/></a></div></div><div className="import-panel"><Icon name="upload" size={26}/><strong>{loading ? 'Reviewing file…' : preview ? 'Ready to confirm import' : file ? file.name : 'Choose a prepared CSV'}</strong><span>{preview ? `${preview.rowCount} row(s) found. Review the first rows below, then confirm.` : 'Choose the register type and upload its CivicPath template.'}</span>{canManage ? <><select value={entityType} onChange={(event) => { setEntityType(event.target.value); setFile(null); setPreview(null); }}><option value="projects">Project register</option><option value="grants">Grant register</option></select><label className="secondary-button upload-button">Choose CSV<input type="file" accept=".csv,text/csv" onChange={choose}/></label></> : <p className="settings-readonly-note">Organisation Administrators and Portfolio Managers can import registers.</p>}</div>{preview ? <div className="import-preview"><div className="import-preview-head"><b>Import preview</b><span>{preview.rowCount} row(s)</span></div><div className="import-table">{preview.headers.map((header) => <b key={header}>{header}</b>)}{preview.preview.flatMap((row, index) => preview.headers.map((header) => <span key={`${index}-${header}`}>{row[header] || '—'}</span>))}</div><div className="import-preview-actions"><small>Confirming imports these records to this Council only. Review ownership, dates and amounts after import.</small><button className="primary-button" type="button" onClick={commit} disabled={importing}>{importing ? 'Importing…' : `Import ${preview.rowCount} ${entityType}`}</button></div></div> : null}</section>;
}

export function SetupChecklist({ projectCount = 0, hasStrategy = false, isAdmin = false }) {
  const items = [
    { done: isAdmin, title: 'Confirm the workspace owner and operating contact', to: '/settings' },
    { done: projectCount > 0, title: 'Add or import the Council’s priority projects', to: '/portfolio' },
    { done: hasStrategy, title: 'Create a strategy delivery register or import adopted actions', to: '/strategy-delivery' },
    { done: false, title: 'Invite the colleagues who will own, contribute to or review the work', to: '/settings' },
  ];
  const done = items.filter((item) => item.done).length;
  return <section className="setup-checklist"><div><p className="card-eyebrow">Guided setup</p><h2>Set up the first useful operating view.</h2><p>Start small: a clear owner, the priority project register, the adopted action register and the people who will keep it current.</p></div><div className="setup-progress"><b>{done}/{items.length}</b><span>foundational steps complete</span></div><ol>{items.map((item) => <li key={item.title} className={item.done ? 'is-done' : ''}><i>{item.done ? '✓' : '•'}</i><span>{item.title}</span><Link to={item.to}>{item.done ? 'Review' : 'Start'} <Icon name="arrow" size={13}/></Link></li>)}</ol></section>;
}
