import Joi from 'joi';
import { Priority, FundingPathway, WorkItem, EvidenceItem, ReadinessAssessment, CivicProject } from '../models/index.js';
import { recordAudit } from '../services/audit.js';
import { calculateReadinessScore } from '../utils/readiness.js';

const prioritySchema = Joi.object({ title: Joi.string().max(200).required(), planReference: Joi.string().max(160).allow('', null), outcomeArea: Joi.string().max(100).allow('', null) });
const pathwaySchema = Joi.object({ projectId: Joi.string().uuid().required(), sourceName: Joi.string().max(200).required(), sourceType: Joi.string().valid('grant', 'loan', 'council', 'partner', 'private', 'other').default('grant'), fit: Joi.string().valid('strong', 'possible', 'watch').default('possible'), potentialAmount: Joi.number().min(0).allow(null), dueDate: Joi.date().iso().allow(null), status: Joi.string().valid('watching', 'preparing', 'submitted', 'awarded', 'not_successful', 'closed').default('watching'), note: Joi.string().allow('', null) });
const workItemSchema = Joi.object({ projectId: Joi.string().uuid().allow(null), grantId: Joi.string().uuid().allow(null), ownerId: Joi.string().uuid().allow(null), title: Joi.string().max(240).required(), workType: Joi.string().valid('action', 'grant_task', 'decision', 'risk').default('action'), status: Joi.string().valid('not_started', 'in_progress', 'blocked', 'complete').default('not_started'), priority: Joi.string().valid('low', 'medium', 'high', 'critical').default('medium'), dueDate: Joi.date().iso().allow(null), detail: Joi.string().allow('', null), impact: Joi.number().integer().min(1).max(5).allow(null), likelihood: Joi.number().integer().min(1).max(5).allow(null) });
const readinessSchema = Joi.object({ scopeScore: Joi.number().integer().min(0).max(5).required(), costScore: Joi.number().integer().min(0).max(5).required(), approvalsScore: Joi.number().integer().min(0).max(5).required(), partnerScore: Joi.number().integer().min(0).max(5).required(), fundingScore: Joi.number().integer().min(0).max(5).required(), deliveryScore: Joi.number().integer().min(0).max(5).required(), assessmentNote: Joi.string().allow('', null) });
const evidenceSchema = Joi.object({ projectId: Joi.string().uuid().allow(null), grantId: Joi.string().uuid().allow(null), title: Joi.string().max(240).required(), evidenceType: Joi.string().valid('document', 'metric', 'decision_record', 'link', 'other').default('document'), externalUrl: Joi.string().uri().allow('', null), source: Joi.string().max(240).allow('', null), isVerified: Joi.boolean().default(false) });

async function validated(schema, input, res) {
  const { value, error } = schema.validate(input, { stripUnknown: true });
  if (error) { res.status(422).json({ error: error.message }); return null; }
  return value;
}

export async function listPriorities(req, res, next) { try { return res.json({ data: await Priority.findAll({ where: { ...req.tenant, status: 'active' }, order: [['title', 'ASC']] }) }); } catch (error) { return next(error); } }
export async function createPriority(req, res, next) { try { const value = await validated(prioritySchema, req.body, res); if (!value) return; const record = await Priority.create({ ...value, organizationId: req.tenant.organizationId }); await recordAudit(req, { entityType: 'priority', entityId: record.id, action: 'created' }); return res.status(201).json({ data: record }); } catch (error) { return next(error); } }
export async function listPathways(req, res, next) { try { return res.json({ data: await FundingPathway.findAll({ where: req.tenant, order: [['dueDate', 'ASC']] }) }); } catch (error) { return next(error); } }
export async function createPathway(req, res, next) { try { const value = await validated(pathwaySchema, req.body, res); if (!value) return; const project = await CivicProject.findOne({ where: { ...req.tenant, id: value.projectId } }); if (!project) return res.status(404).json({ error: 'Project not found.' }); const record = await FundingPathway.create({ ...value, organizationId: req.tenant.organizationId }); await recordAudit(req, { entityType: 'funding_pathway', entityId: record.id, action: 'created' }); return res.status(201).json({ data: record }); } catch (error) { return next(error); } }
export async function listWorkItems(req, res, next) { try { return res.json({ data: await WorkItem.findAll({ where: req.tenant, order: [['dueDate', 'ASC']] }) }); } catch (error) { return next(error); } }
export async function createWorkItem(req, res, next) { try { const value = await validated(workItemSchema, req.body, res); if (!value) return; const record = await WorkItem.create({ ...value, organizationId: req.tenant.organizationId }); await recordAudit(req, { entityType: 'work_item', entityId: record.id, action: 'created', metadata: { workType: record.workType } }); return res.status(201).json({ data: record }); } catch (error) { return next(error); } }
export async function assessReadiness(req, res, next) { try { const value = await validated(readinessSchema, req.body, res); if (!value) return; const project = await CivicProject.findOne({ where: { ...req.tenant, id: req.params.projectId } }); if (!project) return res.status(404).json({ error: 'Project not found.' }); const score = calculateReadinessScore(value); const record = await ReadinessAssessment.create({ ...value, score, projectId: project.id, organizationId: req.tenant.organizationId }); await recordAudit(req, { entityType: 'readiness_assessment', entityId: record.id, action: 'created', metadata: { score } }); return res.status(201).json({ data: record }); } catch (error) { return next(error); } }
export async function listEvidence(req, res, next) { try { return res.json({ data: await EvidenceItem.findAll({ where: req.tenant, order: [['createdAt', 'DESC']] }) }); } catch (error) { return next(error); } }
export async function createEvidence(req, res, next) { try { const value = await validated(evidenceSchema, req.body, res); if (!value) return; const record = await EvidenceItem.create({ ...value, organizationId: req.tenant.organizationId }); await recordAudit(req, { entityType: 'evidence', entityId: record.id, action: 'created' }); return res.status(201).json({ data: record }); } catch (error) { return next(error); } }
