import React from 'react';
import { fundingVelocity } from '../lib/demoData';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Icon } from '../components/Icon';
import { ChartCard } from '../components/ChartCard';

const pathways = [
  { name: 'Regional housing partnership program', project: 'Regional workforce housing pathway', fit: 'Strong fit', type: 'Partner pathway', amount: '$1.5m', date: '15 Nov 2026', status: 'Preparing' },
  { name: 'Sustainable Communities capital round', project: 'Livestock & freight services precinct', fit: 'Strong fit', type: 'Grant pathway', amount: '$1.2m', date: '28 Feb 2027', status: 'Watching' },
  { name: 'Regional Development Trust', project: 'Water-smart agribusiness capability program', fit: 'Possible fit', type: 'Grant pathway', amount: '$350k', date: '01 Dec 2026', status: 'Watching' },
  { name: 'Renewable Energy Zone benefits program', project: 'Renewable energy workforce transition program', fit: 'Possible fit', type: 'Grant pathway', amount: '$500k', date: '30 Apr 2027', status: 'Watching' },
];

export default function FundingPage() { return <main className="page-content funding-page"><div className="page-toolbar"><div><p className="page-intro">A funding pathway is a strategic option—not a grant application until the project is ready.</p></div><button className="primary-button" type="button"><Icon name="plus" size={16}/> Add funding pathway</button></div><section className="funding-kpis"><article><span>Potential funding</span><strong>$3.55m</strong><small>Across 4 active pathways</small></article><article><span>Strong-fit pathways</span><strong>2</strong><small>Two project teams can progress now</small></article><article><span>Next key deadline</span><strong>15 Nov</strong><small>Housing partnership program</small></article></section><section className="funding-layout"><ChartCard eyebrow="Pipeline outlook" title="Funding pathway value by month"><div className="chart-box tall"><ResponsiveContainer width="100%" height="100%"><AreaChart data={fundingVelocity} margin={{ top: 20, right: 20, left: -25, bottom: 0 }}><defs><linearGradient id="fundingPath" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#234c55" stopOpacity=".32"/><stop offset="100%" stopColor="#234c55" stopOpacity="0"/></linearGradient></defs><CartesianGrid stroke="#dce4e0" vertical={false} strokeDasharray="2 4"/><XAxis dataKey="month" axisLine={false} tickLine={false}/><YAxis tickFormatter={(v) => `$${v}m`} axisLine={false} tickLine={false}/><Tooltip/><Area type="stepAfter" dataKey="value" stroke="#234c55" strokeWidth={2.4} fill="url(#fundingPath)"/></AreaChart></ResponsiveContainer></div></ChartCard><section className="readiness-lens"><p className="card-eyebrow">Funding-readiness lens</p><h3>Fundable work begins before a funding round opens.</h3><div className="lens-list"><p><b>2</b><span>projects have a clear funding fit and delivery case</span></p><p><b>2</b><span>projects need further scope, evidence or partner work</span></p><p><b>1</b><span>project remains an early-stage strategic opportunity</span></p></div><button className="text-action" type="button">View readiness guidance <Icon name="arrow" size={15}/></button></section></section><section className="pathway-table"><div className="panel-heading"><div><p className="card-eyebrow">Active pathways</p><h2>Move when the fit is right.</h2></div><button className="secondary-button" type="button">Export pathway report <Icon name="external" size={15}/></button></div><div className="pathway-head"><span>Funding pathway</span><span>Project</span><span>Fit</span><span>Potential</span><span>Next date</span><span>Status</span></div>{pathways.map((pathway) => <div className="pathway-row" key={pathway.name}><div><b>{pathway.name}</b><small>{pathway.type}</small></div><span>{pathway.project}</span><span className={pathway.fit === 'Strong fit' ? 'fit-badge strong' : 'fit-badge'}>{pathway.fit}</span><b>{pathway.amount}</b><span>{pathway.date}</span><span className="status-text">{pathway.status}</span></div>)}</section></main>; }
