/* CivicPath product UI — CivicPath Core and GrantMaestro lifecycle remain visibly distinct but interoperable. */
import React, { useEffect, useMemo, useState } from 'react';
import { toast } from 'react-hot-toast';
import { grants as sampleGrants } from '../lib/demoData';
import { Icon } from '../components/Icon';
import { api } from '../lib/api';

const tabs = ['All', 'Identified', 'Assessing', 'Preparing', 'Submitted', 'Contracted', 'Acquittal'];
const formatMoney = (number) => number >= 1000000 ? `$${(number / 1000000).toFixed(1)}m` : `$${Math.round(number / 1000)}k`;
const titleCase = (value) => value?.replace(/_/g, ' ').replace(/\b\w/g, (letter) => letter.toUpperCase()) || 'Identified';
const formatDate = (value) => value ? new Intl.DateTimeFormat('en-AU', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(value)) : 'No date set';
const toGrant = (grant) => ({ id: grant.id, name: grant.title, funder: grant.funder, project: grant.projectId ? 'Linked CivicPath project' : 'Unlinked grant record', amount: Number(grant.awardedAmount || grant.requestedAmount || 0), requestedAmount: Number(grant.requestedAmount || 0), status: titleCase(grant.status), statusKey: grant.status, due: formatDate(grant.status === 'acquitting' ? grant.acquittalDueDate : grant.dueDate), progress: ({ identified: 12, assessing: 28, preparing: 56, submitted: 72, awarded: 84, contracted: 89, acquitting: 94, acquitted: 100, not_successful: 100, withdrawn: 100 }[grant.status] || 18) });

function AddGrantModal({ close, onCreated, projects }) {
  const [form, setForm] = useState({ title: '', funder: '', projectId: '', requestedAmount: '', status: 'identified', dueDate: '', notes: '' });
  const [saving, setSaving] = useState(false); const update = (key) => (event) => setForm((current) => ({ ...current, [key]: event.target.value }));
  const submit = async (event) => { event.preventDefault(); setSaving(true); try { const response = await api.post('/grants', { ...form, projectId: form.projectId || null, requestedAmount: form.requestedAmount ? Number(form.requestedAmount) : null, dueDate: form.dueDate || null }); onCreated(toGrant(response.data.data)); toast.success('Grant added to the lifecycle workspace.'); close(); } catch (error) { toast.error(error.response?.data?.error || 'The grant could not be created.'); } finally { setSaving(false); } };
  return <div className="modal-backdrop" role="presentation"><form className="modal-panel" onSubmit={submit}><div className="modal-head"><div><p className="card-eyebrow">GrantMaestro lifecycle</p><h2>Add a grant</h2></div><button type="button" className="modal-close" onClick={close} aria-label="Close">×</button></div><p className="modal-intro">Capture a funding opportunity early, then coordinate the evidence, tasks, approvals and acquittal from one shared record.</p><div className="modal-grid"><label>Grant title<input required autoFocus value={form.title} onChange={update('title')} placeholder="e.g. Regional infrastructure enabling works"/></label><label>Funder<input required value={form.funder} onChange={update('funder')} placeholder="Funding body or program"/></label><label>Linked CivicPath project<select value={form.projectId} onChange={update('projectId')}><option value="">No project linked yet</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><label>Lifecycle stage<select value={form.status} onChange={update('status')}><option value="identified">Identified</option><option value="assessing">Assessing</option><option value="preparing">Preparing</option><option value="submitted">Submitted</option><option value="contracted">Contracted</option><option value="acquitting">Acquitting</option></select></label><label>Funding sought (AUD)<input type="number" min="0" value={form.requestedAmount} onChange={update('requestedAmount')} placeholder="0"/></label><label>Key date<input type="date" value={form.dueDate} onChange={update('dueDate')}/></label><label className="modal-full">Internal note<textarea value={form.notes} onChange={update('notes')} placeholder="Why is this opportunity worth assessing and what must happen next?"/></label></div><div className="modal-actions"><button type="button" className="secondary-button" onClick={close}>Cancel</button><button type="submit" className="primary-button" disabled={saving}>{saving ? 'Saving…' : 'Add grant'} <Icon name="arrow" size={15}/></button></div></form></div>;
}

export default function GrantsPage() {
  const [active, setActive] = useState('All'); const [records, setRecords] = useState(sampleGrants); const [projects, setProjects] = useState([]); const [modalOpen, setModalOpen] = useState(false); const [usingSample, setUsingSample] = useState(true);
  useEffect(() => { let mounted = true; Promise.all([api.get('/grants'), api.get('/projects')]).then(([grantsResponse, projectsResponse]) => { if (!mounted) return; setRecords(grantsResponse.data.data.map(toGrant)); setProjects(projectsResponse.data.data); setUsingSample(false); }).catch(() => { if (mounted) setUsingSample(true); }); return () => { mounted = false; }; }, []);
  const shown = useMemo(() => active === 'All' ? records : records.filter((grant) => active === 'Acquittal' ? ['acquitting', 'acquitted'].includes(grant.statusKey) : grant.statusKey === active.toLowerCase()), [active, records]);
  const totalValue = records.reduce((sum, grant) => sum + grant.amount, 0); const attention = records.filter((grant) => ['preparing', 'assessing'].includes(grant.statusKey)).length;
  const addCreated = (grant) => { setRecords((current) => [grant, ...current]); setUsingSample(false); };
  return <main className="page-content grants-page"><div className="page-toolbar"><p className="page-intro">The GrantMaestro lifecycle, connected where it adds value to a CivicPath project portfolio.</p><button className="primary-button" type="button" onClick={() => setModalOpen(true)}><Icon name="plus" size={16}/> Add grant</button></div>{usingSample && <p className="data-note">Displaying protected sample records while the live grant workspace is unavailable.</p>}<section className="grant-summary-strip"><div><p>Grant portfolio</p><strong>{formatMoney(totalValue)}</strong><span>requested and contracted</span></div><div><p>On track</p><strong>{records.filter((grant) => ['contracted', 'submitted'].includes(grant.statusKey)).length}</strong><span>grants in delivery or post-submission</span></div><div><p>Needs attention</p><strong>{attention}</strong><span>grants in assessment or preparation</span></div><div className="lifecycle-path"><p>Lifecycle</p><ol><li className="complete">Identify</li><li className="complete">Assess</li><li className="active">Prepare</li><li>Submit</li><li>Deliver</li><li>Acquit</li></ol></div></section><div className="grant-tabs">{tabs.map((tab) => <button type="button" key={tab} className={active === tab ? 'is-active' : ''} onClick={() => setActive(tab)}>{tab}</button>)}</div><section className="grant-cards">{shown.map((grant) => <article className="grant-card" key={grant.id}><div className="grant-card-head"><span className={`grant-status ${grant.statusKey}`}>{grant.status}</span><button className="ellipsis" type="button">•••</button></div><h2>{grant.name}</h2><p className="funder">{grant.funder}</p><div className="grant-amount"><span>Funding amount</span><strong>{formatMoney(grant.amount)}</strong></div><div className="grant-project"><Icon name="folder" size={16}/><span>{grant.project}</span></div><div className="grant-progress"><div><span>Application and evidence progress</span><b>{grant.progress}%</b></div><i><em style={{ width: `${grant.progress}%` }}/></i></div><div className="grant-card-foot"><span>Key date: <b>{grant.due}</b></span><button type="button">Open lifecycle <Icon name="arrow" size={15}/></button></div></article>)}</section>{modalOpen && <AddGrantModal close={() => setModalOpen(false)} onCreated={addCreated} projects={projects}/>}</main>;
}
