import React from 'react';
import { Link } from 'react-router-dom';
import './AccountLifecyclePage.css';

function LegalShell({ eyebrow, title, children }) {
  return <main className="account-page account-page-simple"><section className="account-content"><article className="account-form-wrap legal-page"><Link className="account-mobile-brand legal-brand" to="/login"><img src="/civicpath-quartermark.png" alt="CivicPath"/> CivicPath</Link><p className="card-eyebrow">{eyebrow}</p><h1>{title}</h1>{children}<p className="legal-meta">Version 1.0 · 6 October 2026 · These pages apply to the CivicPath service. For a question or request, use the <Link to="/contact">protected contact form</Link>.</p></article></section></main>;
}

export function TermsPage() {
  return <LegalShell eyebrow="CivicPath service terms" title="Clear conditions for Council use."><div className="legal-copy"><section><h2>1. CivicPath service</h2><p>CivicPath is a Council workspace for strategy delivery, portfolio readiness, funding pathways, grant lifecycle visibility and quarterly reporting. The service helps users organise and review Council information; it does not make decisions for a Council, provide legal, financial or procurement advice, or guarantee funding or project outcomes.</p></section><section><h2>2. Account authority and access</h2><p>The person registering confirms they are authorised to create the Council workspace. Organisation Administrators are responsible for keeping access appropriate, using the People &amp; Access controls to invite or remove staff, and maintaining at least two active administrators where practical.</p></section><section><h2>3. Council information</h2><p>The Council retains responsibility for the accuracy, currency and lawful use of information entered into CivicPath. Do not upload passwords, access codes, payment-card details or information that the Council is not entitled to process in the service.</p></section><section><h2>4. Subscription, payment and Council Proof</h2><p>Published fees are in Australian dollars and exclude GST. Australian billing addresses attract GST through Stripe where configured. Access begins only after Stripe confirms payment. Council Proof is a paid 60-day workspace; its $495 fee is credited against the first annual CivicPath subscription when the stated conversion conditions are met.</p></section><section><h2>5. Availability and support</h2><p>CivicPath aims to provide a reliable service but does not promise uninterrupted availability. Use the in-product support form for access, billing, data or technical issues. Security and service incidents are triaged according to impact and urgency.</p></section><section><h2>6. Suspension and termination</h2><p>Access may be suspended where payment is overdue, security is at risk, or use materially breaches these terms. A Council may manage its subscription through the Stripe billing portal where available. Termination and data-handling requests are managed through the protected contact route.</p></section></div></LegalShell>;
}

export function PrivacyPage() {
  return <LegalShell eyebrow="CivicPath privacy notice" title="How CivicPath handles Council and contact information."><div className="legal-copy"><section><h2>1. What is collected</h2><p>CivicPath processes account and workspace information, including Council contact details, account roles, billing identifiers supplied to Stripe, portfolio and strategy records, grant workflow information, support submissions, and limited technical logs needed for security and service operation.</p></section><section><h2>2. Why it is used</h2><p>Information is used to provide the workspace, authenticate users, administer subscriptions, respond to support, protect public forms, maintain audit trails and improve service reliability. Public Portfolio Readiness Pulse leads are stored separately from Council tenant data.</p></section><section><h2>3. Service providers and hosting</h2><p>CivicPath is intended to operate on Binary Lane infrastructure, uses AWS SES for outbound transactional email and AWS S3 for private attachments where configured. Stripe processes card payments and billing portal functions. Zoho Mail is used for inward correspondence and replies. Providers process information only for the relevant service function.</p></section><section><h2>4. Access, security and retention</h2><p>Information is tenant-scoped so Council records are not available to other Councils. Platform access follows least-privilege controls, with MFA required for System Administrators. CivicPath retains operational records only for as long as needed for the service, security, legal obligations and agreed commercial administration; a production retention schedule must be applied before launch.</p></section><section><h2>5. Your choices</h2><p>Use the protected contact form to request access or correction of personal information, ask a question about privacy, or unsubscribe from optional marketing updates. Marketing consent is optional for public assessments and is not required to receive a requested resource.</p></section></div></LegalShell>;
}
