import React, { useState } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { api } from '../lib/api';
import { AltchaVerification } from '../components/AltchaVerification';
import './AccountLifecyclePage.css';

function Brand() { return <Link className="account-mobile-brand" to="/login"><img src="/gate-mark.png" alt=""/> CivicPath</Link>; }

export function ForgotPasswordPage() {
  const [email, setEmail] = useState(''); const [altcha, setAltcha] = useState(''); const [key, setKey] = useState(0); const [error, setError] = useState(''); const [submitted, setSubmitted] = useState(false); const [loading, setLoading] = useState(false);
  const submit = async (event) => { event.preventDefault(); setError(''); if (!altcha) return setError('Please complete the verification check first.'); setLoading(true); try { await api.post('/auth/password-reset/request', { email, altcha, honeypot: '' }); setSubmitted(true); } catch (requestError) { setError(requestError.response?.data?.error || 'The password reset request could not be sent. Please try again.'); setAltcha(''); setKey((n) => n + 1); } finally { setLoading(false); } };
  return <main className="account-page account-page-simple"><section className="account-content"><div className="account-form-wrap narrow"><Brand/><p className="card-eyebrow">Account recovery</p><h2>Reset your password</h2>{submitted ? <div className="account-success"><b>Check your inbox</b><p>If a current CivicPath account uses that email address, a secure reset link has been sent. It expires in 60 minutes.</p><Link className="primary-button" to="/login">Back to sign in</Link></div> : <><p className="account-lead">Enter your work email. For security, the same confirmation is shown whether or not the address is recognised.</p><form className="account-form" onSubmit={submit}><label>Work email<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} autoComplete="email" required/></label><AltchaVerification key={key} challengeUrl="/v1/auth/account-challenge?purpose=password_reset" onVerified={setAltcha}/>{error ? <p className="form-message">{error}</p> : null}<button className="primary-button account-submit" disabled={loading || !altcha}>{loading ? <><i className="inline-spinner"/> Sending secure link…</> : 'Send password reset link'}</button><p className="account-signin"><Link to="/login">Return to sign in</Link></p></form></>}</div></section></main>;
}

export function ResetPasswordPage() {
  const [params] = useSearchParams(); const navigate = useNavigate(); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [error, setError] = useState(''); const [success, setSuccess] = useState(false); const [loading, setLoading] = useState(false);
  const token = params.get('token') || '';
  const submit = async (event) => { event.preventDefault(); setError(''); if (!token) return setError('This reset link is incomplete. Request a fresh password reset link.'); if (password !== confirm) return setError('The two password entries do not match.'); setLoading(true); try { await api.post('/auth/password-reset/confirm', { token, password }); setSuccess(true); window.setTimeout(() => navigate('/login'), 2200); } catch (requestError) { setError(requestError.response?.data?.error || 'This reset link could not be used. Request a fresh one.'); } finally { setLoading(false); } };
  return <main className="account-page account-page-simple"><section className="account-content"><div className="account-form-wrap narrow"><Brand/><p className="card-eyebrow">Account recovery</p><h2>Choose a new password</h2>{success ? <div className="account-success"><b>Password updated</b><p>Your password has been reset. Redirecting you to the sign-in page.</p></div> : <form className="account-form" onSubmit={submit}><label>New password<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="new-password" minLength="12" required/></label><label>Confirm new password<input type="password" value={confirm} onChange={(event) => setConfirm(event.target.value)} autoComplete="new-password" minLength="12" required/></label><small className="account-hint">Use at least 12 characters. Signing in on other devices will require your new password.</small>{error ? <p className="form-message">{error}</p> : null}<button className="primary-button account-submit" disabled={loading}>{loading ? <><i className="inline-spinner"/> Updating password…</> : 'Update password'}</button><p className="account-signin"><Link to="/forgot-password">Request a new reset link</Link></p></form>}</div></section></main>;
}

export function RegistrationSuccessPage() {
  return <main className="account-page account-page-simple"><section className="account-content"><div className="account-form-wrap narrow"><Brand/><p className="card-eyebrow">Secure checkout complete</p><h2>Thank you — confirming your CivicPath access</h2><div className="account-success"><b>Stripe is confirming payment</b><p>Once payment is verified, CivicPath sends a confirmation email and activates the Council workspace. This usually takes only a moment.</p><p>If you do not receive confirmation shortly, use the CivicPath contact form and select Billing.</p><Link className="primary-button" to="/login">Go to sign in</Link></div></div></section></main>;
}
